"""Pitch Master — Multi-language support."""

LANGUAGES = {
    "EN": {
        "lang_code": "EN",
        "lang_name": "English",
        "flag": "🇬🇧",
        # Sidebar
        "sidebar_title": "🎯 Pitch Master",
        "sidebar_mode": "Mode",
        "sidebar_build": "Build Mode",
        "sidebar_audit": "Audit Mode",
        "sidebar_provider": "Provider",
        "sidebar_model": "Model",
        "sidebar_lang": "Language",
        "sidebar_disclaimer": (
            "**Disclaimer:** This is a heuristic v0.1 score, not investment advice. "
            "Pitch Master does not decide whether a company is investable."
        ),
        # Main title
        "title_build": "🎯 Pitch Master",
        "title_audit": "🎯 Pitch Master — Audit",
        # Build Mode
        "build_header": "Build your pitch",
        "build_subheader": "Answer the questions below. The more detail you give, the better the output.",
        "field_company": "Company name *",
        "field_oneliner": "One-liner (what you do) *",
        "field_problem": "Problem you solve *",
        "field_solution": "Your solution *",
        "field_whynow": "Why now? (timing, trends, regulation)",
        "field_market": "Market (TAM/SAM, growth rate)",
        "field_bizmodel": "Business model (pricing, unit economics)",
        "field_traction": "Traction (revenue, users, pilots, growth)",
        "field_team": "Team (founders, backgrounds, unfair advantage)",
        "field_ask": "Ask (how much, what for)",
        "btn_generate": "Generate Pitch",
        "error_missing_fields": "Please fill in at least: Company name, One-liner, Problem, Solution.",
        "spinner_generating": "Generating pitch...",
        "generated_header": "Generated Pitch",
        "export_md": "Export MD",
        "export_txt": "Export TXT",
        "export_docx": "Export DOCX",
        "export_pdf": "Export PDF",
        "saved": "Saved: {path}",
        "error_generic": "Error: {error}",
        # Audit Mode
        "audit_header": "Audit a pitch deck",
        "audit_subheader": "Upload a PDF pitch deck to get a PEF-100 score and improvement suggestions.",
        "upload_pdf": "Upload PDF",
        "spinner_extracting": "Extracting text from PDF...",
        "pdf_error": "PDF Error: {error}",
        "pdf_pages": "Pages",
        "pdf_words": "Words",
        "pef_score": "PEF-100 Score",
        "layer_breakdown": "Layer Breakdown",
        "layer_attention": "Attention",
        "layer_understanding": "Understanding",
        "layer_belief": "Belief",
        "layer_trust": "Trust",
        "layer_fomo": "FOMO",
        "penalties_header": "Penalties",
        "penalty_friction": "Cognitive Friction",
        "penalty_risk": "Perceived Risk",
        "red_flags": "Red Flags Found",
        "text_preview": "Text Preview (first 2000 chars)",
        "llm_audit_header": "LLM-Powered Audit",
        "btn_deep_audit": "Run Deep Audit",
        "spinner_auditing": "Running deep audit...",
        "export_audit_md": "Export Audit MD",
        "export_audit_txt": "Export Audit TXT",
        "export_audit_docx": "Export Audit DOCX",
        "export_audit_pdf": "Export Audit PDF",
        "footer_disclaimer": (
            "PEF-100 is a heuristic v0.1 score. The real PEF-100 is a 23-variable measurement system "
            "validated through inter-rater reliability and factor analysis."
        ),
        # PEF Variables (translated for UI)
        "var_novelty": "Novelty",
        "var_relevance": "Relevance",
        "var_energy": "Energy",
        "var_timing": "Timing",
        "var_clarity": "Clarity",
        "var_compression": "Compression",
        "var_structure": "Structure",
        "var_visual_cog": "Visual Cognition",
        "var_proof": "Proof",
        "var_traction": "Traction",
        "var_mechanism": "Mechanism",
        "var_market_logic": "Market Logic",
        "var_competence": "Competence",
        "var_authenticity": "Authenticity",
        "var_founder_fit": "Founder Fit",
        "var_exec_cred": "Exec Credibility",
        "var_upside": "Upside",
        "var_momentum": "Momentum",
        "var_scarcity": "Scarcity",
        "var_asymmetry": "Asymmetry",
    },
    "IT": {
        "lang_code": "IT",
        "lang_name": "Italiano",
        "flag": "🇮🇹",
        # Sidebar
        "sidebar_title": "🎯 Pitch Master",
        "sidebar_mode": "Modalita",
        "sidebar_build": "Modalita Costruisci",
        "sidebar_audit": "Modalita Audita",
        "sidebar_provider": "Provider",
        "sidebar_model": "Modello",
        "sidebar_lang": "Lingua",
        "sidebar_disclaimer": (
            "**Avviso:** Questo e un punteggio euristico v0.1, non un consiglio finanziario. "
            "Pitch Master non decide se una startup e investibile."
        ),
        # Main title
        "title_build": "🎯 Pitch Master",
        "title_audit": "🎯 Pitch Master — Audit",
        # Build Mode
        "build_header": "Costruisci il tuo pitch",
        "build_subheader": "Rispondi alle domande qui sotto. Piu dettagli dai, migliore sara l'output.",
        "field_company": "Nome azienda *",
        "field_oneliner": "One-liner (cosa fate) *",
        "field_problem": "Problema che risolvete *",
        "field_solution": "La vostra soluzione *",
        "field_whynow": "Perche ora? (timing, trend, regolamentazione)",
        "field_market": "Mercato (TAM/SAM, tasso di crescita)",
        "field_bizmodel": "Business model (prezzi, unit economics)",
        "field_traction": "Traction (ricavi, utenti, pilot, crescita)",
        "field_team": "Team (founders, background, vantaggio competitivo)",
        "field_ask": "Richiesta (quanto, per cosa)",
        "btn_generate": "Genera Pitch",
        "error_missing_fields": "Compila almeno: Nome azienda, One-liner, Problema, Soluzione.",
        "spinner_generating": "Generazione pitch in corso...",
        "generated_header": "Pitch Generato",
        "export_md": "Esporta MD",
        "export_txt": "Esporta TXT",
        "export_docx": "Esporta DOCX",
        "export_pdf": "Esporta PDF",
        "saved": "Salvato: {path}",
        "error_generic": "Errore: {error}",
        # Audit Mode
        "audit_header": "Audita un pitch deck",
        "audit_subheader": "Carica un PDF del pitch deck per ottenere un punteggio PEF-100 e suggerimenti di miglioramento.",
        "upload_pdf": "Carica PDF",
        "spinner_extracting": "Estrazione testo dal PDF in corso...",
        "pdf_error": "Errore PDF: {error}",
        "pdf_pages": "Pagine",
        "pdf_words": "Parole",
        "pef_score": "Punteggio PEF-100",
        "layer_breakdown": "Scomposizione Livelli",
        "layer_attention": "Attenzione",
        "layer_understanding": "Comprensione",
        "layer_belief": "Credibilita",
        "layer_trust": "Fiducia",
        "layer_fomo": "FOMO",
        "penalties_header": "Penalita",
        "penalty_friction": "Fatica Cognitiva",
        "penalty_risk": "Rischio Percepito",
        "red_flags": "Red Flags Trovati",
        "text_preview": "Anteprima Testo (primi 2000 caratteri)",
        "llm_audit_header": "Audit LLM",
        "btn_deep_audit": "Esegui Audit Approfondito",
        "spinner_auditing": "Audit in corso...",
        "export_audit_md": "Esporta Audit MD",
        "export_audit_txt": "Esporta Audit TXT",
        "export_audit_docx": "Esporta Audit DOCX",
        "export_audit_pdf": "Esporta Audit PDF",
        "footer_disclaimer": (
            "PEF-100 e un punteggio euristico v0.1. Il vero PEF-100 e un sistema di misurazione a 23 variabili "
            "validato attraverso affidabilita inter-rater e analisi fattoriale."
        ),
        # PEF Variables (translated for UI)
        "var_novelty": "Novita",
        "var_relevance": "Rilevanza",
        "var_energy": "Energia",
        "var_timing": "Timing",
        "var_clarity": "Chiarita",
        "var_compression": "Compressione",
        "var_structure": "Struttura",
        "var_visual_cog": "Cognizione Visiva",
        "var_proof": "Prove",
        "var_traction": "Traction",
        "var_mechanism": "Meccanismo",
        "var_market_logic": "Logica di Mercato",
        "var_competence": "Competenza",
        "var_authenticity": "Autenticita",
        "var_founder_fit": "Founder Fit",
        "var_exec_cred": "Credibilita Leadership",
        "var_upside": "Potenziale",
        "var_momentum": "Momentum",
        "var_scarcity": "Scarsita",
        "var_asymmetry": "Asimmetria",
    },
    "PT": {
        "lang_code": "PT",
        "lang_name": "Portugues",
        "flag": "🇧🇷",
        # Sidebar
        "sidebar_title": "🎯 Pitch Master",
        "sidebar_mode": "Modo",
        "sidebar_build": "Modo Construir",
        "sidebar_audit": "Modo Auditar",
        "sidebar_provider": "Provider",
        "sidebar_model": "Modelo",
        "sidebar_lang": "Idioma",
        "sidebar_disclaimer": (
            "**Aviso:** Esta e uma pontuacao heuristica v0.1, nao um conselho financeiro. "
            "Pitch Master nao decide se uma startup e investivel."
        ),
        # Main title
        "title_build": "🎯 Pitch Master",
        "title_audit": "🎯 Pitch Master — Auditoria",
        # Build Mode
        "build_header": "Construa seu pitch",
        "build_subheader": "Responda as perguntas abaixo. Quanto mais detalhes, melhor o resultado.",
        "field_company": "Nome da empresa *",
        "field_oneliner": "One-liner (o que voces fazem) *",
        "field_problem": "Problema que resolvem *",
        "field_solution": "Sua solucao *",
        "field_whynow": "Por que agora? (timing, tendencias, regulacao)",
        "field_market": "Mercado (TAM/SAM, taxa de crescimento)",
        "field_bizmodel": "Modelo de negocio (precificacao, unit economics)",
        "field_traction": "Traction (receita, usuarios, pilotos, crescimento)",
        "field_team": "Time (founders, historico, vantagem competitiva)",
        "field_ask": "Pedido (quanto, para que)",
        "btn_generate": "Gerar Pitch",
        "error_missing_fields": "Preencha pelo menos: Nome da empresa, One-liner, Problema, Solucao.",
        "spinner_generating": "Gerando pitch...",
        "generated_header": "Pitch Gerado",
        "export_md": "Exportar MD",
        "export_txt": "Exportar TXT",
        "export_docx": "Exportar DOCX",
        "export_pdf": "Exportar PDF",
        "saved": "Salvo: {path}",
        "error_generic": "Erro: {error}",
        # Audit Mode
        "audit_header": "Auditar um pitch deck",
        "audit_subheader": "Envie um PDF do pitch deck para obter uma pontuacao PEF-100 e sugestoes de melhoria.",
        "upload_pdf": "Enviar PDF",
        "spinner_extracting": "Extraindo texto do PDF...",
        "pdf_error": "Erro PDF: {error}",
        "pdf_pages": "Paginas",
        "pdf_words": "Palavras",
        "pef_score": "Pontuacao PEF-100",
        "layer_breakdown": "Composicao por Camadas",
        "layer_attention": "Atencao",
        "layer_understanding": "Compreensao",
        "layer_belief": "Credibilidade",
        "layer_trust": "Confianca",
        "layer_fomo": "FOMO",
        "penalties_header": "Penalidades",
        "penalty_friction": "Friccao Cognitiva",
        "penalty_risk": "Risco Percebido",
        "red_flags": "Bandeiras Vermelhas Encontradas",
        "text_preview": "Visualizacao do Texto (primeiros 2000 caracteres)",
        "llm_audit_header": "Auditoria LLM",
        "btn_deep_audit": "Executar Auditoria Profunda",
        "spinner_auditing": "Executando auditoria profunda...",
        "export_audit_md": "Exportar Auditoria MD",
        "export_audit_txt": "Exportar Auditoria TXT",
        "export_audit_docx": "Exportar Auditoria DOCX",
        "export_audit_pdf": "Exportar Auditoria PDF",
        "footer_disclaimer": (
            "PEF-100 e uma pontuacao heuristica v0.1. O verdadeiro PEF-100 e um sistema de medicao "
            "com 23 variaveis, validado por confiabilidade entre avaliadores e analise fatorial."
        ),
        # PEF Variables (translated for UI)
        "var_novelty": "Novidade",
        "var_relevance": "Relevancia",
        "var_energy": "Energia",
        "var_timing": "Timing",
        "var_clarity": "Clareza",
        "var_compression": "Compressao",
        "var_structure": "Estrutura",
        "var_visual_cog": "Cognicao Visual",
        "var_proof": "Provas",
        "var_traction": "Traction",
        "var_mechanism": "Mecanismo",
        "var_market_logic": "Logica de Mercado",
        "var_competence": "Competencia",
        "var_authenticity": "Autenticidade",
        "var_founder_fit": "Founder Fit",
        "var_exec_cred": "Credibilidade da Lideranca",
        "var_upside": "Potencial",
        "var_momentum": "Momentum",
        "var_scarcity": "Escassez",
        "var_asymmetry": "Assimetria",
    },
    "ES": {
        "lang_code": "ES",
        "lang_name": "Espanol",
        "flag": "🇪🇸",
        # Sidebar
        "sidebar_title": "🎯 Pitch Master",
        "sidebar_mode": "Modo",
        "sidebar_build": "Modo Construir",
        "sidebar_audit": "Modo Auditar",
        "sidebar_provider": "Provider",
        "sidebar_model": "Modelo",
        "sidebar_lang": "Idioma",
        "sidebar_disclaimer": (
            "**Aviso:** Esta es una puntuacion heuristica v0.1, no un consejo financiero. "
            "Pitch Master no decide si una startup es invertible."
        ),
        # Main title
        "title_build": "🎯 Pitch Master",
        "title_audit": "🎯 Pitch Master — Auditoria",
        # Build Mode
        "build_header": "Construye tu pitch",
        "build_subheader": "Responde las preguntas de abajo. Cuantos mas detalles, mejor sera el resultado.",
        "field_company": "Nombre de la empresa *",
        "field_oneliner": "One-liner (que hacen) *",
        "field_problem": "Problema que resuelven *",
        "field_solution": "Tu solucion *",
        "field_whynow": "Por que ahora? (timing, tendencias, regulacion)",
        "field_market": "Mercado (TAM/SAM, tasa de crecimiento)",
        "field_bizmodel": "Modelo de negocio (precios, unit economics)",
        "field_traction": "Traction (ingresos, usuarios, pilotos, crecimiento)",
        "field_team": "Equipo (founders, historial, ventaja competitiva)",
        "field_ask": "Pedido (cuanto, para que)",
        "btn_generate": "Generar Pitch",
        "error_missing_fields": "Completa al menos: Nombre de empresa, One-liner, Problema, Solucion.",
        "spinner_generating": "Generando pitch...",
        "generated_header": "Pitch Generado",
        "export_md": "Exportar MD",
        "export_txt": "Exportar TXT",
        "export_docx": "Exportar DOCX",
        "export_pdf": "Exportar PDF",
        "saved": "Guardado: {path}",
        "error_generic": "Error: {error}",
        # Audit Mode
        "audit_header": "Auditar un pitch deck",
        "audit_subheader": "Sube un PDF del pitch deck para obtener una puntuacion PEF-100 y sugerencias de mejora.",
        "upload_pdf": "Subir PDF",
        "spinner_extracting": "Extrayendo texto del PDF...",
        "pdf_error": "Error PDF: {error}",
        "pdf_pages": "Paginas",
        "pdf_words": "Palabras",
        "pef_score": "Puntuacion PEF-100",
        "layer_breakdown": "Desglose por Capas",
        "layer_attention": "Atencion",
        "layer_understanding": "Comprension",
        "layer_belief": "Credibilidad",
        "layer_trust": "Confianza",
        "layer_fomo": "FOMO",
        "penalties_header": "Penalizaciones",
        "penalty_friction": "Friccion Cognitiva",
        "penalty_risk": "Riesgo Percibido",
        "red_flags": "Banderas Rojas Encontradas",
        "text_preview": "Vista Previa del Texto (primeros 2000 caracteres)",
        "llm_audit_header": "Auditoria LLM",
        "btn_deep_audit": "Ejecutar Auditoria Profunda",
        "spinner_auditing": "Ejecutando auditoria profunda...",
        "export_audit_md": "Exportar Auditoria MD",
        "export_audit_txt": "Exportar Auditoria TXT",
        "export_audit_docx": "Exportar Auditoria DOCX",
        "export_audit_pdf": "Exportar Auditoria PDF",
        "footer_disclaimer": (
            "PEF-100 es una puntuacion heuristica v0.1. El verdadero PEF-100 es un sistema de medicion "
            "con 23 variables, validado por confiabilidad entre evaluadores y analisis factorial."
        ),
        # PEF Variables (translated for UI)
        "var_novelty": "Novedad",
        "var_relevance": "Relevancia",
        "var_energy": "Energia",
        "var_timing": "Timing",
        "var_clarity": "Claridad",
        "var_compression": "Compresion",
        "var_structure": "Estructura",
        "var_visual_cog": "Cognicion Visual",
        "var_proof": "Evidencia",
        "var_traction": "Traction",
        "var_mechanism": "Mecanismo",
        "var_market_logic": "Logica de Mercado",
        "var_competence": "Competencia",
        "var_authenticity": "Autenticidad",
        "var_founder_fit": "Founder Fit",
        "var_exec_cred": "Credibilidad del Liderazgo",
        "var_upside": "Potencial",
        "var_momentum": "Momentum",
        "var_scarcity": "Escasez",
        "var_asymmetry": "Asimetria",
    },
}

DEFAULT_LANG = "EN"


def get_lang(code: str | None = None) -> dict:
    """Get language dictionary by code. Falls back to EN."""
    if code and code in LANGUAGES:
        return LANGUAGES[code]
    return LANGUAGES[DEFAULT_LANG]


def get_lang_codes() -> list[str]:
    """Get list of available language codes."""
    return list(LANGUAGES.keys())
